name: BungeeBridgeC
main: me.dommi2212.BungeeBridge.BungeeBridgeC
version: 1.5.0
author: dommi2212
commands:
  packetmanager:
    description: Used to manage and monitor packets.
    aliases: [packetman,packetmonitor,packetmon]